name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4
        with:
          install: true

      - run: mise x pnpm -- pnpm install --frozen-lockfile
      - run: mise x pnpm -- pnpm run check
